# Generated by Django 5.0.7 on 2024-07-19 21:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='group')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('verbose_name', models.CharField(max_length=25, verbose_name='verbose name')),
                ('genre', models.CharField(choices=[('attribute', 'attribute'), ('filter', 'filter'), ('both', 'both')], max_length=25, verbose_name='genre')),
                ('symbole', models.CharField(choices=[('None', 'None'), ('icon', 'icon'), ('color', 'color')], max_length=25, verbose_name='symbole')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='level')),
                ('levels_afterthis', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('previous_father_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('all_childes_id', models.TextField(blank=True, default='')),
                ('post_product', models.CharField(default='product', max_length=10, verbose_name='post or product')),
                ('father_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', related_query_name='childs', to='main.category', verbose_name='father category')),
                ('filters', models.ManyToManyField(blank=True, to='main.filter', verbose_name='filters')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('level',),
            },
        ),
    ]
